// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SistemaCadastroOS2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OSModel", b =>
                {
                    b.Property<int>("NumeroOS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumeroOS"));

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTime>("DataExecucaoServico")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomeDoCliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeDoPrestador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TituloServico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorDoServico")
                        .HasColumnType("numeric");

                    b.HasKey("NumeroOS");

                    b.ToTable("OSModels");
                });
#pragma warning restore 612, 618
        }
    }
}
